export const lightTheme = {
  body: "#FFF",
  text: "#363537",
  toggleBorder: "#FFF",
  background: "#363537",
  greetingsTextColor: "#9799AC",
  greetingsHeaderColor: "#164D59",
  greetingsBackgroundVideoDisplay: "none",
  greetingsBackground: "none",
  greetings: {
    signUpBackground: "rgba(205, 168, 112, 0.75)",
    findOutBackground: "rgba(205, 168, 112, 0.15);",
    signUpText: "#164D59",
    findOutText: "#C19B61",
    userIconDarkDisplay: "none",
    userIconLightDisplay: "block",
    googleIcon: "none",
    googleIconLight: "block",
    appIcon: "none",
    appIconLight: "block",
  },
  //   greetings
};
export const darkTheme = {
  body: "#363537",
  text: "#FAFAFA",
  toggleBorder: "#6B8096",
  background: "#999",
  greetingsTextColor: "#FBFDFC",
  greetingsHeaderColor: "#FFF",
  greetingsBackgroundVideoDisplay: "block",
  greetingsBackground:
    "linear-gradient(0deg,rgba(0, 0, 0, 0.75) 0%,rgba(0, 0, 0, 0.6) 100%)",
  greetings: {
    signUpBackground: "#CDA870",
    findOutBackground: "rgba(255, 255, 255, 0.15)",
    signUpText: "#272727",
    findOutText: "#CDA870",
    userIconDarkDisplay: "block",
    userIconLightDisplay: "none",
    googleIconLight: "none",
    googleIcon: "block",
    appIconLight: "none",
    appIcon: "block",
  },
};
